#standard
import glob

SConscript([
	'unit_tests/SConscript'
])

Import('env_base')
env_tommath = env_base.Clone()

env_tommath['CPPPATH'].append('#'+Dir('.').path);
env_tommath.StaticLibrary('#lib/tommath', glob.glob('*.c*'))
