#!/bin/sh

TOP_DIR=`pwd`

if [ "$1" == "clean" ]; then
	clear
	cd src
	python scons/scons.py -c
	cd $TOP_DIR
	rm -f p2p_gui p2p_nogui p2p_nogui_static sqlite3 DB rightside_up upside_down download/*
else
	clear && clear
	cd src
	python scons/scons.py
	cd $TOP_DIR
	cp src/p2p_gui ./
	cp src/p2p_nogui ./
	cp src/p2p_nogui_static ./
	cp src/libsqlite3/sqlite3 ./
fi
