#!/bin/sh

TOP_DIR=`pwd`

if [ "$1" == "clean" ]; then
	#clean up
	clear
	cd src
	python scons/scons.py -c
	cd $TOP_DIR
	rm -f p2p_gui p2p_nogui p2p_nogui_static DB rightside_up upside_down download/*
else
	#build
	clear && clear
	cd src
	python scons/scons.py
	cd $TOP_DIR
	cp src/p2p_gui ./
	cp src/p2p_nogui ./
	cp src/p2p_nogui_static ./
fi
