#!/bin/sh

TOP_DIR=`pwd`

if [ "$1" == "build" ]; then
	#build
	cd src
	scons -j2
	cd $TOP_DIR
	cp src/p2p_gui ./
	cp src/p2p_nogui ./
elif [ "$1" == "clean" ] ; then
	#clean up
	cd src
	scons -c
	cd $TOP_DIR
	rm -f p2p_gui p2p_nogui
	rm -f download/*
	rm -f hash/*
elif [ "$1" == "push" ] ; then
	if [ ! -f "p2p_gui" ] ; then
		echo "p2p_gui missing"
	elif [ ! -f "p2p_nogui" ] ; then
		echo "p2p_nogui missing"
	fi

else
	echo "options:"
	echo "  build - build program"
	echo "  clean - clean everything"
	echo "  push  - push out servers"
fi
