import string
from waflib.Tools import waf_unit_test

def build(bld):
	for x in bld.path.ant_glob('*.cpp'):
		bld(
			features = 'cxx cprogram test',
			source = x,
			target = str(x)[:str(x).rfind('.')] + '.bin',
			uselib = ['boost', 'platform'],
			uselib_local = [
				'local_include',
				'net'
			]
		)
