def build(bld):
	bld.recurse('unit_tests')
	bld(
		features = 'cxx cxxstlib', 
		source = bld.path.ant_glob('*.cpp'),
		target = 'p2p',
		use = ['platform', 'boost'],
		uselib_local = 'local_include'
	)
