def build(bld):
	bld.recurse('unit_tests')
	bld(
		features = 'cxx cxxstlib', 
		source = bld.path.ant_glob('*.cpp'),
		target = 'p2p',
		uselib = ['boost', 'platform'],
		uselib_local = 'local_include'
	)
