Import('env_base')

src = [
	'block_arbiter.cpp',
	'database_init.cpp',
	'database_table_blacklist.cpp',
	'database_table_download.cpp',
	'database_table_hash.cpp',
	'database_table_preferences.cpp',
	'database_table_prime.cpp',
	'database_table_search.cpp',
	'database_table_share.cpp',
	'encryption.cpp',
	'hash_tree.cpp',
	'number_generator.cpp',
	'path.cpp',
	'p2p.cpp',
	'request_generator.cpp',
	'share_index.cpp'
]

SConscript([
	'unit_tests/SConstruct'
])

env_base.StaticLibrary('p2p', src)
