#site_scons
import gtkmm

#std
import sys

Import('env_base')

src_gui = [
	'gui.cpp',
	'gui_about.cpp',
	'gui_statusbar_main.cpp',
	'gui_vbox_search.cpp',
	'gui_window_download.cpp',
	'gui_window_download_status.cpp',
	'gui_window_preferences.cpp',
	'gui_window_upload.cpp',
	'main_gui.cpp'
]

#nogui only
src_nogui = [
	'main_nogui.cpp'
]

#gui environment
env_gui = env_base.Clone()
gtkmm.setup(env_gui)

#link
env_gui.Program('p2p_gui', src_gui)
env_base.Program('p2p_nogui', src_nogui)
