#site_scons
import boost

#std
import glob

Import('env')

static_libs = [
	boost.static_lib('date_time'),
	boost.static_lib('system'),
	boost.static_lib('thread')
]

env.Program('sim', glob.glob('*.cpp') + static_libs)
