#site_scons
import boost
import system

#std
import glob
import fnmatch
import os
import sys

env = Environment()
boost.env_setup(env)
system.env_setup(env)

static_libs = [
	boost.static_lib('date_time'),
	boost.static_lib('system'),
	boost.static_lib('thread')
]

env.Program('sim', glob.glob('*.cc') + static_libs)
