def build(bld):
	bld(
		features = ['cxx', 'cprogram'],
		source = bld.path.ant_glob('*.cpp'),
		target = 'http',
		uselib = ['boost', 'platform'],
		uselib_local = [
			'local_include',
			'net'
		]
	)
