def build(bld):
	bld(
		features = ['cxx', 'cprogram'],
		source = bld.path.ant_glob('*.cpp'),
		target = 'http',
		lib = [
			'boost_system',
			'boost_filesystem',
			'boost_regex',
			'boost_thread',
			'pthread'
		],
		uselib_local = [
			'local_include',
			'net'
		],
		libpath = ['/usr/local/lib']
	)
