#site_scons
import system

Import('env_base')
env_sqlite = env_base.Clone()

#compile as multithreaded http://www.sqlite.org/compile.html#threadsafe
#Setting =2 doesn't serialize all access, but requires locking such that
#no two threads use the same DB connection at the same time.
env_sqlite['CPPDEFINES'].append('SQLITE_THREADSAFE=2')

#enable full text search
env_sqlite['CPPDEFINES'].append('SQLITE_ENABLE_FTS3')
env_sqlite['CPPDEFINES'].append('SQLITE_ENABLE_FTS3_PARENTHESIS')

#remove libdl dependency by disabling dynamic module loading (not used anyways)
env_sqlite['CPPDEFINES'].append('SQLITE_OMIT_LOAD_EXTENSION');

env_sqlite.StaticLibrary('#lib/sqlite3', 'sqlite3.c')
env_sqlite.Program('#bin/sqlite3', ['shell.c'])
