def build(bld):
	bld(
		features = ['cxx', 'cprogram'],
		source = bld.path.ant_glob('*.cpp'),
		target = 'CLI',
		uselib = ['boost', 'platform'],
		uselib_local = [
			'local_include',
			'p2p',
			'net',
			'tommath',
			'sqlite3'
		]
	)
