import glob
import sys
platform = sys.platform

env = Environment()
if platform == 'win32':
	env['CCFLAGS'].append('/Ox')
if platform == 'linux2':
	env['CCFLAGS'].append('-O3')

files = glob.glob('*.c')
StaticLibrary('libtommath', files)
