#site_scons
import glob
import unit_test

Import('env_base')
unit_test.run(env_base)

Clean('.', glob.glob('*.db'))
Clean('.', glob.glob('*.db-journal'))
Clean('download','download')
Clean('load','load')
Clean('share','share')
Clean('tmp','tmp')
Clean('.p2p','.p2p')
