#!/bin/sh

export PATH="/usr/local/bin:/sbin"
export HTTP="/usr/local/bin/http"
export HTTP_OPTIONS="--web_root=/var/www --max_upload_rate=8192"
export HTTP_PID="/var/lock/http.pid"
export USER="root"
export GROUP="root"

case "$1" in
  start)
	echo "Starting http server..."
	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $HTTP_PID --chuid $USER --group $GROUP --exec $HTTP -- $HTTP_OPTIONS || echo "http already started"
	;;
  stop)
	echo "Stopping http server..."
	start-stop-daemon --stop --quiet --oknodo --pidfile $HTTP_PID 
	;;

  restart)
	echo "Restarting http server..."
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $HTTP_PID 
	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $HTTP_PID --chuid $USER --group $GROUP --exec $HTTP -- $HTTP_OPTIONS || echo "http already started"
	;;
  *)
	echo "Usage: /etc/init.d/http {start|stop|restart}"
	exit 1
esac

exit 0
