#site_scons
import boost
import system
import unit_test

env = Environment()
system.env_setup(env)
boost.env_setup(env)

env.unit_test('convert.cc')
env.unit_test('contiguous_map.cc')
env.unit_test('contiguous_set.cc')

env.unit_test([
	'DB_blacklist.cc',
	'../DB_blacklist.o',
	'../logger.o',
	boost.static_lib('thread')
])

env.unit_test([
	'DB_client_preferences.cc',
	'../DB_client_preferences.o',
	'../logger.o',
	boost.static_lib('thread')
])

env.unit_test([
	'DB_download.cc',
	'../DB_download.o',
	'../logger.o',
	boost.static_lib('filesystem'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'DB_prime.cc',
	'../DB_prime.o',
	'../logger.o',
	boost.static_lib('thread')
])

env.unit_test([
	'DB_search.cc',
	'../DB_search.o',
	'../logger.o',
	boost.static_lib('thread')
])

env.unit_test([
	'DB_server_preferences.cc',
	'../DB_server_preferences.o',
	'../logger.o',
	boost.static_lib('thread')
])

env.unit_test([
	'DB_share.cc',
	'../DB_share.o',
	'../logger.o',
	boost.static_lib('thread')
])

env.unit_test([
	'hash_tree.cc',
	'../hash_tree.o',
	'../DB_blacklist.o',
	'../logger.o',
	'../sha.o',
	boost.static_lib('filesystem'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'request_generator.cc',
	'../request_generator.o',
	'../logger.o',
	boost.static_lib('thread')
])

Clean('database','database')
Clean('hash','hash')
Clean('share','share')
