#site_scons
import boost
import sqlite3
import tommath
import unit_test

Import('env_base')

env_base.unit_test([
	'database_table_blacklist.cpp',
	'../database_table_blacklist.cpp',
	'../database_init.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library()
])

env_base.unit_test([
	'database_table_download.cpp',
	'../database_table_download.cpp',
	'../database_table_blacklist.cpp',
	'../database_init.cpp',
	'../database_table_hash.cpp',
	'../hash_tree.cpp',
	'../request_generator.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library()
])

env_base.unit_test([
	'database_table_preferences.cpp',
	'../database_table_preferences.cpp',
	'../database_init.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library()
])

env_base.unit_test([
	'database_table_prime.cpp',
	'../database_table_prime.cpp',
	'../database_init.cpp',
	'../request_generator.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library(),
	tommath.static_library()
])

env_base.unit_test([
	'database_table_search.cpp',
	'../database_table_search.cpp',
	'../database_table_blacklist.cpp',
	'../database_init.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library()
])

env_base.unit_test([
	'database_table_share.cpp',
	'../database_table_share.cpp',
	'../database_table_blacklist.cpp',
	'../database_init.cpp',
	'../database_table_hash.cpp',
	'../hash_tree.cpp',
	'../request_generator.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library()
])

env_base.unit_test([
	'encryption.cpp',
	'../encryption.cpp',
	'../database_init.cpp',
	'../database_table_prime.cpp',
	'../number_generator.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library(),
	tommath.static_library()
])

env_base.unit_test([
	'hash_tree.cpp',
	'../hash_tree.cpp',
	'../database_init.cpp',
	'../database_table_blacklist.cpp',
	'../database_table_hash.cpp',
	'../request_generator.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library()
])

env_base.unit_test([
	'request_generator.cpp',
	'../request_generator.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])

Clean('DB','DB')
Clean('DB-journal', 'DB-journal')
Clean('hash','hash')
Clean('share','share')
Clean('upside_down','upside_down')
Clean('rightside_up','rightside_up')
