#site_scons
import boost
import unit_test

Import('env')

env.unit_test([
	'atomic_bool.cpp',
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'atomic_int.cpp',
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'convert.cpp',
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'contiguous_map.cpp',
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'contiguous_set.cpp',
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'database_connection.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'database_table_blacklist.cpp',
	'../database_table_blacklist.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'database_table_download.cpp',
	'../database_table_download.cpp',
	'../database_table_blacklist.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../database_table_hash.cpp',
	'../hash_tree.cpp',
	'../request_generator.cpp',
	'../sha.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('filesystem'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'database_table_preferences.cpp',
	'../database_table_preferences.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'database_table_prime.cpp',
	'../database_table_prime.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../request_generator.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'database_table_search.cpp',
	'../database_table_search.cpp',
	'../database_table_blacklist.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('filesystem'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'database_table_share.cpp',
	'../database_table_share.cpp',
	'../database_table_blacklist.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../database_table_hash.cpp',
	'../hash_tree.cpp',
	'../request_generator.cpp',
	'../sha.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'encryption.cpp',
	'../encryption.cpp',
	'../CMWC4096.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../database_table_prime.cpp',
	'../number_generator.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'hash_tree.cpp',
	'../hash_tree.cpp',
	'../database_connection.cpp',
	'../database_init.cpp',
	'../database_table_blacklist.cpp',
	'../database_table_hash.cpp',
	'../request_generator.cpp',
	'../sha.cpp',
	'../speed_calculator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('filesystem'),
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'locking_shared_ptr.cpp',
	boost.static_lib('system'),
	boost.static_lib('thread')
])

env.unit_test([
	'request_generator.cpp',
	'../request_generator.cpp',
	boost.static_lib('date_time'),
	boost.static_lib('thread')
])

env.unit_test([
	'sha.cpp',
	'../sha.cpp',
	boost.static_lib('system'),
	boost.static_lib('thread')
])

Clean('DB','DB')
Clean('DB-journal', 'DB-journal')
Clean('hash','hash')
Clean('share','share')
Clean('upside_down','upside_down')
Clean('rightside_up','rightside_up')
