def build(bld):
	#bld.recurse('http')
	bld.recurse('unit_tests')
	bld(
		features = 'cxx cxxstlib', 
		source = bld.path.ant_glob('*.cpp'),
		target = 'net',
		uselib = ['boost', 'platform'],
		uselib_local = 'local_include'
	)
