#site_scons
import boost
import sqlite3
import unit_test

Import('env_base')

env_base.unit_test([
	'atomic_bool.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])

env_base.unit_test([
	'atomic_int.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])

env_base.unit_test([
	'buffer.cpp'
])


env_base.unit_test([
	'contiguous_map.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])

env_base.unit_test([
	'contiguous_set.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])

env_base.unit_test([
	'convert.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])

env_base.unit_test([
	'database_connection.cpp',
	boost.static_library('date_time'),
	boost.static_library('filesystem'),
	boost.static_library('system'),
	boost.static_library('thread'),
	sqlite3.static_library()
])

env_base.unit_test([
	'locking_shared_ptr.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])

env_base.unit_test([
	'RC4.cpp'
])

env_base.unit_test([
	'sha.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])

env_base.unit_test([
	'thread_pool.cpp',
	boost.static_library('date_time'),
	boost.static_library('system'),
	boost.static_library('thread')
])
