#!/bin/sh

mkdir -p seek-bound/100k/
cd seek-bound/100k/
for i in `seq 1 1000`; do 
	mkdir -p files-$i; 
	for j in `seq 1 100`; do 
		dd if=/dev/zero of=files-$i/$j bs=100k count=1 2> /dev/null; 
	done; 
done

find ./seek-bound/100k/ | grep 'files.*/.' | sed 's#./#http://192.168.1.7:8080/#' > http-load.100k.urls
