#!/usr/bin/perl

$VM_count = 4;
$IP_begin = '192.168.254.';
$IP_range_start = '2';

if(not defined(@ARGV[0])){
	print "usage: $0 <mode>\n";
	print "modes: off, push, start\n";
}

if(@ARGV[0] eq "shutdown"){
	shutdown_vm();
}
if(@ARGV[0] eq "push"){
	push_servers();
}
if(@ARGV[0] eq "start"){
	start();
}

sub shutdown_vm
{
	for($x=$IP_range_start; $x < $IP_range_start + $VM_count; ++$x){
		print "sending shut down command to $IP_begin$x\n";
		system("ssh -i ~/.ssh/vm root\@$IP_begin$x shutdown now -h");
	}
}

sub push_servers
{
	for($x=$IP_range_start; $x < $IP_range_start + $VM_count; ++$x){
		print "pushing to $IP_begin$x\n";
		system("scp -i ~/.ssh/vm sqlite3 $IP_begin$x:/home/smack");
		system("ssh -i ~/.ssh/vm $IP_begin$x killall -q screen");
		system("ssh -i ~/.ssh/vm $IP_begin$x \"echo \\\"DELETE FROM blacklist;\\\" |./sqlite3 DB\"");
		system("scp -i ~/.ssh/vm p2p_nogui $IP_begin$x:/home/smack");
		system("ssh -i ~/.ssh/vm $IP_begin$x screen -d -m ./p2p_nogui");
	}
}

sub start
{
	for($x=0; $x<$VM_count; ++$x){
		my $pid = fork;
		die("fork failed: $!") unless defined($pid);
		if($pid == 0){
			#this is child process
			if($x<10){
				$port = "330$x";
			}else{
				$port = "33$x";
			}
			system("/usr/bin/VBoxHeadless -vrdpport $port -startvm \"Debian CLI $x\"");
			exit();
		}else{
			#error if too many VMs starting concurrently
			sleep(20);
		}
	}

	#wait for children to die
	while(wait() != -1){}
}
