def build(bld):
	bld.recurse('unit_tests')
	bld(
		features = 'c cxx cxxstlib', 
		source = bld.path.ant_glob('*.c*'),
		target = 'tommath',
		includes = '.',
		uselib = ['boost', 'platform'],
		uselib_local = 'local_include'
	)
